[package]
name = "mio-echo-server"
version = "0.1.0"
authors = ["djp <duanjp8617@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = "0.6"
bytes = "0.3"
slab  = "0.4"
log = "0.4.8"